# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_RK2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_RK2(object):
    def setupUi(self, ventana_RK2, vector_rk2):
        ventana_RK2.setObjectName("ventana_RK2")
        ventana_RK2.resize(1030, 636)
        self.tabla2 = QtWidgets.QTableWidget(ventana_RK2)
        self.tabla2.setGeometry(QtCore.QRect(5, 20, 1020, 611))
        self.tabla2.setObjectName("tabla2")
        self.tabla2.setColumnCount(7)
        self.tabla2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla2.setHorizontalHeaderItem(6, item)

        self.retranslateUi(ventana_RK2)
        QtCore.QMetaObject.connectSlotsByName(ventana_RK2)

        self.tabla2.setColumnWidth(0, 50)
        self.tabla2.setColumnWidth(1, 150)
        self.tabla2.setColumnWidth(2, 150)
        self.tabla2.setColumnWidth(3, 150)
        self.tabla2.setColumnWidth(4, 150)
        self.tabla2.setColumnWidth(5, 150)
        self.tabla2.setColumnWidth(6, 150)

        self.tabla2.setRowCount(len(vector_rk2))
        self.tabla2.setColumnCount(7)
        for i in range (len(vector_rk2)):
            self.tabla2.setItem(i, 0, QtWidgets.QTableWidgetItem(str(vector_rk2[i][0])))
            self.tabla2.setItem(i, 1, QtWidgets.QTableWidgetItem(str(vector_rk2[i][1])))
            self.tabla2.setItem(i, 2, QtWidgets.QTableWidgetItem(str(vector_rk2[i][2])))
            self.tabla2.setItem(i, 3, QtWidgets.QTableWidgetItem(str(vector_rk2[i][5])))
            self.tabla2.setItem(i, 4, QtWidgets.QTableWidgetItem(str(vector_rk2[i][8])))
            self.tabla2.setItem(i, 5, QtWidgets.QTableWidgetItem(str(vector_rk2[i][11])))
            self.tabla2.setItem(i, 6, QtWidgets.QTableWidgetItem(str(vector_rk2[i][12])))

    def retranslateUi(self, ventana_RK2):
        _translate = QtCore.QCoreApplication.translate
        ventana_RK2.setWindowTitle(_translate("ventana_RK2", "Tabla Rungee Kutta 2"))
        item = self.tabla2.horizontalHeaderItem(0)
        item.setText(_translate("ventana_RK2", "t"))
        item = self.tabla2.horizontalHeaderItem(1)
        item.setText(_translate("ventana_RK2", "A"))
        item = self.tabla2.horizontalHeaderItem(2)
        item.setText(_translate("ventana_RK2", "k1"))
        item = self.tabla2.horizontalHeaderItem(3)
        item.setText(_translate("ventana_RK2", "k2"))
        item = self.tabla2.horizontalHeaderItem(4)
        item.setText(_translate("ventana_RK2", "k3"))
        item = self.tabla2.horizontalHeaderItem(5)
        item.setText(_translate("ventana_RK2", "k4"))
        item = self.tabla2.horizontalHeaderItem(6)
        item.setText(_translate("ventana_RK2", "An+1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_RK2 = QtWidgets.QWidget()
    ui = Ui_ventana_RK2()
    ui.setupUi(ventana_RK2)
    ventana_RK2.show()
    sys.exit(app.exec_())
