# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_RK1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_RK1(object):
    def setupUi(self, ventana_RK1,  vector_rk1):
        ventana_RK1.setObjectName("ventana_RK1")
        ventana_RK1.resize(1030, 633)
        self.tabla1 = QtWidgets.QTableWidget(ventana_RK1)
        self.tabla1.setGeometry(QtCore.QRect(5, 10, 1020, 611))
        self.tabla1.setObjectName("tabla1")
        self.tabla1.setColumnCount(7)
        self.tabla1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla1.setHorizontalHeaderItem(6, item)

        self.tabla1.setColumnWidth(0, 50)
        self.tabla1.setColumnWidth(1, 150)
        self.tabla1.setColumnWidth(2, 150)
        self.tabla1.setColumnWidth(3, 150)
        self.tabla1.setColumnWidth(4, 150)
        self.tabla1.setColumnWidth(5, 150)
        self.tabla1.setColumnWidth(6, 150)

        self.retranslateUi(ventana_RK1)
        QtCore.QMetaObject.connectSlotsByName(ventana_RK1)



        self.tabla1.setRowCount(len(vector_rk1))
        self.tabla1.setColumnCount(7)
        print(vector_rk1)
        for i in range(len(vector_rk1)):
            for i in range(len(vector_rk1)):
                self.tabla1.setItem(i, 0, QtWidgets.QTableWidgetItem(str(vector_rk1[i][0])))
                self.tabla1.setItem(i, 1, QtWidgets.QTableWidgetItem(str(vector_rk1[i][1])))
                self.tabla1.setItem(i, 2, QtWidgets.QTableWidgetItem(str(vector_rk1[i][2])))
                self.tabla1.setItem(i, 3, QtWidgets.QTableWidgetItem(str(vector_rk1[i][5])))
                self.tabla1.setItem(i, 4, QtWidgets.QTableWidgetItem(str(vector_rk1[i][8])))
                self.tabla1.setItem(i, 5, QtWidgets.QTableWidgetItem(str(vector_rk1[i][11])))
                self.tabla1.setItem(i, 6, QtWidgets.QTableWidgetItem(str(vector_rk1[i][12])))

    def retranslateUi(self, ventana_RK1):
        _translate = QtCore.QCoreApplication.translate
        ventana_RK1.setWindowTitle(_translate("ventana_RK1", "Table Runge Kutta 1"))
        item = self.tabla1.horizontalHeaderItem(0)
        item.setText(_translate("ventana_RK1", "t"))
        item = self.tabla1.horizontalHeaderItem(1)
        item.setText(_translate("ventana_RK1", "A"))
        item = self.tabla1.horizontalHeaderItem(2)
        item.setText(_translate("ventana_RK1", "k1"))
        item = self.tabla1.horizontalHeaderItem(3)
        item.setText(_translate("ventana_RK1", "k2"))
        item = self.tabla1.horizontalHeaderItem(4)
        item.setText(_translate("ventana_RK1", "k3"))
        item = self.tabla1.horizontalHeaderItem(5)
        item.setText(_translate("ventana_RK1", "k4"))
        item = self.tabla1.horizontalHeaderItem(6)
        item.setText(_translate("ventana_RK1", "An+1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_RK1 = QtWidgets.QWidget()
    ui = Ui_ventana_RK1()
    ui.setupUi(ventana_RK1)
    ventana_RK1.show()
    sys.exit(app.exec_())
